### ISSUE TITLE
Error installing VLCMediaLibraryKit

### ISSUE THREAD

**Issue by gajjartejas** [Mikanbu/VLCMediaLibraryKit#1]
I am trying to install pod for VLC But giving error.

`[!] Error installing VLCMediaLibraryKit
[!] /usr/bin/curl -f -L -o /var/folders/5g/cgjq5vf96vgg5lq95wf81ffw0000gn/T/d20181227-23353-1ms4bwy/file.zip https://mikanbu.com/public/VLCMediaLibraryKit.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: mikanbu.com`

**Comment by Mikanbu** [comment]
Are you still having the issue? Looking at the logs, I would say it is a network problem.

_Just as an information, the package will be moved to a VideoLAN server soon._

**Comment by Mikanbu** [comment]
Closing this issue since the packages were moved to VideoLAN servers.
